{% set name = "tricycle" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tricycle-{{ version }}.tar.gz
  sha256: f56edb4b3e1bed3e2552b1b499b24a2dab47741e92e9b4d806acc5c35c9e6066

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - trio >=0.23.0

test:
  imports:
    - tricycle
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/oremanj/tricycle
  summary: Experimental extensions for Trio, the friendly async I/O library
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE
    - LICENSE.APACHE2
    - LICENSE.MIT

extra:
  recipe-maintainers:
    - dhirschfeld
