{% set name = "tricycle" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tricycle-{{ version }}.tar.gz
  sha256: e203f7f366e22a4ae0224334953cb9d97f56b8d1f8d08c0934dec64736880d7c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - trio >=0.23.0

test:
  imports:
    - tricycle
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/oremanj/tricycle
  summary: Experimental extensions for Trio, the friendly async I/O library
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE
    - LICENSE.APACHE2
    - LICENSE.MIT

extra:
  recipe-maintainers:
    - dhirschfeld
