{% set name = "tricycle" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tricycle-{{ version }}.tar.gz
  sha256: 57d854a61361e3b45b615b069bcf105fb0d6979d534ed7338e26b51d3ed28473

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - trio >=0.15.0
    - trio-typing >=0.5.0

test:
  imports:
    - tricycle
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/oremanj/tricycle
  summary: Experimental extensions for Trio, the friendly async I/O library
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE
    - LICENSE.APACHE2
    - LICENSE.MIT

extra:
  recipe-maintainers:
    - dhirschfeld
